#!/bin/sh

mvn clean
. amazon-selling-partner-api-model-repositoty-clone.sh
mvn io.swagger:swagger-codegen-maven-plugin:generate@apluscontent
mvn io.swagger:swagger-codegen-maven-plugin:generate@authorization
mvn io.swagger:swagger-codegen-maven-plugin:generate@catalogitems
mvn io.swagger:swagger-codegen-maven-plugin:generate@easyship
mvn io.swagger:swagger-codegen-maven-plugin:generate@fbainbound
mvn io.swagger:swagger-codegen-maven-plugin:generate@fbainventory
mvn io.swagger:swagger-codegen-maven-plugin:generate@fbasmallandlight
mvn io.swagger:swagger-codegen-maven-plugin:generate@feeds
mvn io.swagger:swagger-codegen-maven-plugin:generate@finances
mvn io.swagger:swagger-codegen-maven-plugin:generate@fulfillmentinbound
mvn io.swagger:swagger-codegen-maven-plugin:generate@fulfillmentoutbound
mvn io.swagger:swagger-codegen-maven-plugin:generate@listingsitems
mvn io.swagger:swagger-codegen-maven-plugin:generate@listingsrestrictions
mvn io.swagger:swagger-codegen-maven-plugin:generate@merchantfulfillment
mvn io.swagger:swagger-codegen-maven-plugin:generate@messaging
mvn io.swagger:swagger-codegen-maven-plugin:generate@notifications
mvn io.swagger:swagger-codegen-maven-plugin:generate@orders
mvn io.swagger:swagger-codegen-maven-plugin:generate@productfees
mvn io.swagger:swagger-codegen-maven-plugin:generate@productpricing
mvn io.swagger:swagger-codegen-maven-plugin:generate@definitionsproducttypes
mvn io.swagger:swagger-codegen-maven-plugin:generate@reports
mvn io.swagger:swagger-codegen-maven-plugin:generate@sales
mvn io.swagger:swagger-codegen-maven-plugin:generate@sellers
mvn io.swagger:swagger-codegen-maven-plugin:generate@services
mvn io.swagger:swagger-codegen-maven-plugin:generate@shipmentinvoicing
mvn io.swagger:swagger-codegen-maven-plugin:generate@shipping
mvn io.swagger:swagger-codegen-maven-plugin:generate@solicitations
mvn io.swagger:swagger-codegen-maven-plugin:generate@tokens
mvn io.swagger:swagger-codegen-maven-plugin:generate@uploads
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendordirectfulfillmentinventory
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendordirectfulfillmentorders
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendordirectfulfillmentpayments
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendordirectfulfillmentsandboxdata
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendordirectfulfillmentshipping
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendordirectfulfillmenttransactions
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendorinvoices
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendororders
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendorshipments
mvn io.swagger:swagger-codegen-maven-plugin:generate@vendortransactionstatus
